# Generated by Django 4.0 on 2024-01-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ballots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballots',
            name='text_content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
