# Generated by Django 4.0 on 2024-01-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ballots', '0002_ballots_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballots',
            name='content',
        ),
    ]
