# Generated by Django 4.0 on 2024-01-10 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=250)),
                ('full_name', models.CharField(default='Anonymous', max_length=250, null=True)),
                ('avatar', models.ImageField(default='static/Images/Avatar.jpg', upload_to='MyUser/profile_pictures')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('bio', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
